module.exports = {
    content: ["./views/**/*.ejs", "./public/**/*.html"],
    safelist: [
      'bg-gradient-to-r',
      'from-purple-500',
      'via-pink-500', 
      'to-orange-500',
      'from-green-500',
      'to-black',
      'from-black',
      'via-red-500',
      'to-pink-500',
      'bg-blue-600',
      'bg-red-600',
      'bg-yellow-400',
      'bg-pink-500',
      'bg-blue-500',
      'bg-gray-600',
      'bg-blue-700',
      'bg-gray-800',
      'bg-black',
      'bg-indigo-600',
      'bg-green-500',
      'bg-purple-600',
      'bg-orange-500',
      'text-white',
      'text-black',
      'text-gray-700'
    ],
    theme: {
      extend: {},
    },
    plugins: [],
  }
  